ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.rewild.ApplicationKt.module ]
    }
}

database {
    url = ${?DB_URL}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
}

jwt {
    secret = ${?JWT_SECRET}
    issuer = ${?JWT_ISSUER}
    audience = "rewild-api"
}

cookies {
    secure = true
    secure = ${?COOKIES_SECURE}
}

cors {
    allowedOrigin = ${?CORS_ALLOWED_ORIGIN}
}

storage {
    bucketBaseUrl = ${?BUCKET_BASE_URL}
    bucketName = ${?BUCKET_NAME}
    s3Endpoint = ${?S3_ENDPOINT}
    s3AccessKey = ${?S3_ACCESS_KEY}
    s3SecretKey = ${?S3_SECRET_KEY}
}
