/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Creates a new user account and returns a JWT access token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.auth.RegisterRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.auth.AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticates with email and password and returns a JWT access token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.auth.LoginRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.auth.AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh token
         * @description Issues a new access token using the refresh token cookie
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.auth.AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the refresh token and clears the auth cookie
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot password
         * @description Sends a password reset email if the address is registered. Always returns 200 to prevent account enumeration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.auth.ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Request accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password
         * @description Resets the user's password using a valid time-limited token and signs them in
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.auth.ResetPasswordRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.auth.AuthResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns all projects for the authenticated user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Project"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project
         * @description Returns a project by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Project"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Create or update project
         * @description Upserts a project by ID. Path ID takes precedence over any ID in the request body.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.models.Project"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Project"];
                    };
                };
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete project
         * @description Deletes a project and cascades to its associated levels
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List levels
         * @description Returns all levels for the authenticated user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Level"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get level
         * @description Returns a level by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Level ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Level"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Create or update level
         * @description Upserts a level by ID. Path ID takes precedence over any ID in the request body.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Level ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.models.Level"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Level"];
                    };
                };
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete level
         * @description Deletes a level by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Level ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Level deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Bidirectional sync: push dirty local records and pull server-side changes since lastSyncedAt
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.models.SyncRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.SyncResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List assets
         * @description Returns all confirmed assets for the authenticated user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.Asset"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request presigned upload URL
         * @description Validates level ownership and returns a presigned PUT URL for direct upload to object storage
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.models.UploadUrlRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.models.UploadUrlResponse"];
                    };
                };
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm asset upload
         * @description Marks an asset as confirmed after successful direct upload. Purges stale unconfirmed records older than 1 hour.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["com.rewild.models.ConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.rewild.common.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** RegisterRequest */
        "com.rewild.auth.RegisterRequest": {
            /** String */
            email: string;
            /** String */
            password: string;
            /** String */
            username: string;
        };
        /** AuthResponse */
        "com.rewild.auth.AuthResponse": {
            /** String */
            token: string;
        };
        /** LoginRequest */
        "com.rewild.auth.LoginRequest": {
            /** String */
            email: string;
            /** String */
            password: string;
        };
        /** ForgotPasswordRequest */
        "com.rewild.auth.ForgotPasswordRequest": {
            /** String */
            email: string;
        };
        /** ResetPasswordRequest */
        "com.rewild.auth.ResetPasswordRequest": {
            /** String */
            password: string;
            /** String */
            token: string;
        };
        /** ErrorResponse */
        "com.rewild.common.ErrorResponse": {
            /** String */
            error: string;
        };
        /** Project */
        "com.rewild.models.Project": {
            /** Boolean */
            activeOnStartup: boolean;
            /** String */
            description: string;
            /** String */
            id: string;
            /** String */
            levelId?: null | string;
            /** String */
            name: string;
            sceneGraph: components["schemas"]["com.rewild.models.SceneGraph"];
            /** String */
            startEvent: string;
            /** String */
            syncError?: null | string;
            /**
             * Long
             * Format: int64
             */
            syncedAt: number;
            /**
             * Long
             * Format: int64
             */
            updatedAt: number;
            /** String */
            userId?: null | string;
        };
        /** SceneGraph */
        "com.rewild.models.SceneGraph": {
            atmosphere: components["schemas"]["com.rewild.models.Atmosphere"];
            /** List<Container> */
            containers: components["schemas"]["com.rewild.models.Container"][];
        };
        /** Atmosphere */
        "com.rewild.models.Atmosphere": {
            cloudiness: components["schemas"]["kotlinx.serialization.json.JsonElement"];
            dayNightCycle: components["schemas"]["kotlinx.serialization.json.JsonElement2"];
            elevation: components["schemas"]["kotlinx.serialization.json.JsonElement3"];
            foginess: components["schemas"]["kotlinx.serialization.json.JsonElement4"];
            precipitation: components["schemas"]["kotlinx.serialization.json.JsonElement5"];
            temperature: components["schemas"]["kotlinx.serialization.json.JsonElement6"];
            windiness: components["schemas"]["kotlinx.serialization.json.JsonElement7"];
        };
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** JsonPrimitive */
        "kotlinx.serialization.json.JsonPrimitive": components["schemas"]["kotlinx.serialization.json.JsonLiteral"] | components["schemas"]["kotlinx.serialization.json.JsonNull"];
        /** JsonLiteral */
        "kotlinx.serialization.json.JsonLiteral": {
            /** String */
            content: string;
            /** Boolean */
            isString: boolean;
        };
        /** JsonNull */
        "kotlinx.serialization.json.JsonNull": {
            /** String */
            content: string;
            /** Boolean */
            isString: boolean;
        };
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement2": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement3": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement4": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement5": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement6": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement7": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** Container */
        "com.rewild.models.Container": {
            /** String */
            id: string;
            /** String */
            name: string;
            /** List<JsonElement> */
            properties?: null | components["schemas"]["kotlinx.serialization.json.JsonElement"][];
            /** String */
            templateId?: null | string;
            /** String */
            type: string;
            /** Boolean */
            activeOnStartup: boolean;
            /** List<Actor> */
            actors: components["schemas"]["com.rewild.models.Actor"][];
            pod: components["schemas"]["com.rewild.models.ContainerPod"];
        };
        /** JsonElement */
        "kotlinx.serialization.json.JsonElement8": unknown[] | {
            [key: string]: unknown;
        } | components["schemas"]["kotlinx.serialization.json.JsonPrimitive"];
        /** Actor */
        "com.rewild.models.Actor": {
            /** String */
            id: string;
            /** String */
            name: string;
            /** List<JsonElement> */
            properties?: null | components["schemas"]["kotlinx.serialization.json.JsonElement"][];
            /** String */
            templateId?: null | string;
            /** String */
            type: string;
        };
        /** ContainerPod */
        "com.rewild.models.ContainerPod": {
            /** List<Asset3D> */
            asset3D: components["schemas"]["com.rewild.models.Asset3D"][];
        };
        /** Asset3D */
        "com.rewild.models.Asset3D": {
            /** String */
            id: string;
            /** List<Float> */
            position: number[];
            /** List<Float> */
            rotation: number[];
        };
        /** Level */
        "com.rewild.models.Level": {
            /** Boolean */
            activeOnStartup: boolean;
            /** List<Container> */
            containers: components["schemas"]["com.rewild.models.Container"][];
            /** Boolean */
            hasTerrain: boolean;
            /** String */
            id: string;
            /** String */
            name: string;
            /** String */
            projectId: string;
            /** String */
            startEvent: string;
            /** String */
            syncError?: null | string;
            /**
             * Long
             * Format: int64
             */
            syncedAt: number;
            /**
             * Long
             * Format: int64
             */
            updatedAt: number;
            /** String */
            userId?: null | string;
        };
        /** SyncRecord */
        "com.rewild.models.SyncRecord": {
            /** String */
            collection: string;
            /** JsonObject */
            data: {
                [key: string]: unknown;
            };
            /** String */
            id: string;
            /**
             * Long
             * Format: int64
             */
            updatedAt: number;
        };
        /** SyncRequest */
        "com.rewild.models.SyncRequest": {
            /**
             * Long
             * Format: int64
             */
            lastSyncedAt: number;
            /** List<SyncRecord> */
            records: components["schemas"]["com.rewild.models.SyncRecord"][];
        };
        /** SyncResponse */
        "com.rewild.models.SyncResponse": {
            /** List<SyncRecord> */
            records: components["schemas"]["com.rewild.models.SyncRecord"][];
            /**
             * Long
             * Format: int64
             */
            syncedAt: number;
        };
        /** Asset */
        "com.rewild.models.Asset": {
            /** String */
            assetType: string;
            /** String */
            filename: string;
            /** String */
            id: string;
            /** String */
            levelId: string;
            /** String */
            publicUrl: string;
        };
        /** UploadUrlRequest */
        "com.rewild.models.UploadUrlRequest": {
            /** String */
            assetType: string;
            /** String */
            filename: string;
            /** String */
            levelId: string;
        };
        /** UploadUrlResponse */
        "com.rewild.models.UploadUrlResponse": {
            /** String */
            publicUrl: string;
            /** String */
            storageKey: string;
            /** String */
            uploadUrl: string;
        };
        /** ConfirmRequest */
        "com.rewild.models.ConfirmRequest": {
            /** String */
            storageKey: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
