import { styled } from "solid-styled-components";
import { ParentComponent, JSX } from "solid-js";

export type ButtonVariant = "contained" | "outlined";
export type ButtonColor = "primary" | "secondary" | "error";

interface Props {
  icon: IconType;
  size?: "s" | "m" | "l" | "xl";
  style?: JSX.CSSProperties;
}

export const MaterialIcon: ParentComponent<Props> = (props) => {
  const size =
    props.size === "s"
      ? "md-18"
      : props.size === "m"
      ? "md-24"
      : props.size === "l"
      ? "md-36"
      : props.size === "xl"
      ? "md-48"
      : "md-24";

  return (
    <StyledIcon style={props.style} class={`icon material-icons-sharp ${size}`}>
      {props.icon}
    </StyledIcon>
  );
};

export const StyledMaterialIcon: ParentComponent<Props> = (props) => {
  return (
    <MaterialIcon style={{ color: "var(--on-surface-light)" }} {...props}>
      {props.children}
    </MaterialIcon>
  );
};

const StyledIcon = styled.span`
  color: inherit;
  &.md-18 {
    font-size: 18px;
  }
  &.md-24 {
    font-size: 24px;
  }
  &.md-36 {
    font-size: 36px;
  }
  &.md-48 {
    font-size: 48px;
  }
`;

export type IconType =
  | "search"
  | "search"
  | "home"
  | "account_circle"
  | "settings"
  | "done"
  | "info"
  | "check_circle"
  | "delete"
  | "visibility"
  | "shopping_cart"
  | "favorite"
  | "description"
  | "logout"
  | "favorite_border"
  | "lock"
  | "schedule"
  | "language"
  | "help_outline"
  | "face"
  | "manage_accounts"
  | "filter_alt"
  | "verified"
  | "event"
  | "thumb_up"
  | "fingerprint"
  | "dashboard"
  | "login"
  | "calendar_today"
  | "list"
  | "visibility_off"
  | "check_circle outline"
  | "highlight_off"
  | "help"
  | "question_answer"
  | "paid"
  | "task_alt"
  | "date_range"
  | "article"
  | "shopping_bag"
  | "lightbulb"
  | "open_in new"
  | "perm_identity"
  | "trending_up"
  | "history"
  | "credit_card"
  | "account_balance"
  | "delete_outline"
  | "report_problem"
  | "fact_check"
  | "assignment"
  | "verified_user"
  | "arrow_right alt"
  | "star_rate"
  | "account_balance wallet"
  | "autorenew"
  | "analytics"
  | "build"
  | "view_list"
  | "work"
  | "print"
  | "store"
  | "today"
  | "delete_forever"
  | "admin_panel settings"
  | "lock_open"
  | "grade"
  | "code"
  | "savings"
  | "room"
  | "watch_later"
  | "receipt"
  | "update"
  | "add_shopping cart"
  | "contact_support"
  | "power_settings new"
  | "pets"
  | "calendar_month"
  | "done_all"
  | "explore"
  | "bookmark"
  | "note_add"
  | "bookmark_border"
  | "account_box"
  | "reorder"
  | "pending_actions"
  | "shopping_basket"
  | "drag_indicator"
  | "payment"
  | "launch"
  | "supervisor_account"
  | "pending"
  | "touch_app"
  | "zoom_in"
  | "assessment"
  | "thumb_up off alt"
  | "open_in full"
  | "leaderboard"
  | "exit_to app"
  | "done_outline"
  | "preview"
  | "assignment_ind"
  | "card_giftcard"
  | "view_in ar"
  | "published_with changes"
  | "work_outline"
  | "feedback"
  | "timeline"
  | "swap_horiz"
  | "dns"
  | "assignment_turned in"
  | "sync_alt"
  | "flight_takeoff"
  | "label"
  | "stars"
  | "book"
  | "bug_report"
  | "contact_page"
  | "pan_tool"
  | "space_dashboard"
  | "gavel"
  | "alarm"
  | "cached"
  | "translate"
  | "tips_and updates"
  | "edit_calendar"
  | "supervised_user circle"
  | "android"
  | "minimize"
  | "accessibility"
  | "extension"
  | "get_app"
  | "record_voice over"
  | "add_task"
  | "trending_flat"
  | "hourglass_empty"
  | "help_center"
  | "accessibility_new"
  | "thumb_down"
  | "rule"
  | "sticky_note 2"
  | "flutter_dash"
  | "source"
  | "rocket_launch"
  | "dashboard_customize"
  | "support"
  | "find_in page"
  | "question_mark"
  | "settings_applications"
  | "close_fullscreen"
  | "redeem"
  | "ads_click"
  | "announcement"
  | "view_headline"
  | "loyalty"
  | "swap_vert"
  | "group_work"
  | "restore"
  | "arrow_circle right"
  | "dangerous"
  | "euro_symbol"
  | "sensors"
  | "compare_arrows"
  | "nightlight_round"
  | "subject"
  | "privacy_tip"
  | "disabled_by default"
  | "table_view"
  | "https"
  | "toc"
  | "track_changes"
  | "copyright"
  | "arrow_circle up"
  | "bookmarks"
  | "grading"
  | "api"
  | "query_builder"
  | "perm_media"
  | "build_circle"
  | "input"
  | "zoom_out"
  | "view_module"
  | "perm_contact calendar"
  | "backup"
  | "book_online"
  | "open_with"
  | "settings_phone"
  | "circle_notifications"
  | "speaker_notes"
  | "card_membership"
  | "file_present"
  | "label_important"
  | "perm_phone msg"
  | "arrow_circle down"
  | "3d_rotation"
  | "wysiwyg"
  | "pageview"
  | "integration_instructions"
  | "upgrade"
  | "swipe"
  | "trending_down"
  | "change_history"
  | "class"
  | "accessible"
  | "g_translate"
  | "settings_accessibility"
  | "currency_exchange"
  | "offline_bolt"
  | "expand"
  | "production_quantity limits"
  | "model_training"
  | "settings_backup restore"
  | "aspect_ratio"
  | "donut_large"
  | "percent"
  | "segment"
  | "calendar_view month"
  | "view_column"
  | "arrow_circle left"
  | "schedule_send"
  | "maximize"
  | "bookmark_add"
  | "alarm_on"
  | "thumbs_up down"
  | "settings_ethernet"
  | "theaters"
  | "view_agenda"
  | "thumb_down off alt"
  | "important_devices"
  | "invert_colors"
  | "unpublished"
  | "open_in browser"
  | "addchart"
  | "no_accounts"
  | "opacity"
  | "commute"
  | "youtube_searched for"
  | "history_toggle off"
  | "view_week"
  | "tour"
  | "system_update alt"
  | "settings_input antenna"
  | "turned_in"
  | "mark_as unread"
  | "shop"
  | "hide_source"
  | "bookmark_added"
  | "plagiarism"
  | "search_off"
  | "flight_land"
  | "not_started"
  | "assignment_late"
  | "donut_small"
  | "saved_search"
  | "contactless"
  | "highlight_alt"
  | "view_carousel"
  | "settings_input component"
  | "anchor"
  | "turned_in not"
  | "mediation"
  | "assignment_return"
  | "view_quilt"
  | "fit_screen"
  | "all_inbox"
  | "edit_off"
  | "toll"
  | "settings_remote"
  | "flaky"
  | "hourglass_full"
  | "remove_shopping cart"
  | "hotel_class"
  | "shopping_cart checkout"
  | "lock_clock"
  | "balance"
  | "settings_voice"
  | "filter_alt off"
  | "swap_horizontal circle"
  | "online_prediction"
  | "pregnant_woman"
  | "view_sidebar"
  | "event_seat"
  | "next_plan"
  | "vertical_split"
  | "camera_enhance"
  | "restore_from trash"
  | "markunread_mailbox"
  | "data_exploration"
  | "dynamic_form"
  | "calendar_view week"
  | "tab"
  | "rocket"
  | "accessible_forward"
  | "view_stream"
  | "add_to drive"
  | "remove_done"
  | "request_page"
  | "settings_power"
  | "smart_button"
  | "token"
  | "card_travel"
  | "outbox"
  | "terminal"
  | "try"
  | "offline_pin"
  | "calendar_view day"
  | "lock_reset"
  | "rowing"
  | "outlet"
  | "find_replace"
  | "compress"
  | "chrome_reader mode"
  | "settings_brightness"
  | "http"
  | "assignment_returned"
  | "alarm_add"
  | "spellcheck"
  | "backup_table"
  | "info_outline"
  | "play_for work"
  | "new_label"
  | "credit_card off"
  | "restore_page"
  | "fax"
  | "gif"
  | "wifi_protected setup"
  | "generating_tokens"
  | "settings_overscan"
  | "settings_input composite"
  | "quickreply"
  | "density_medium"
  | "view_day"
  | "free_cancellation"
  | "comment_bank"
  | "outbound"
  | "swap_vertical circle"
  | "cancel_schedule send"
  | "line_weight"
  | "polymer"
  | "add_card"
  | "horizontal_split"
  | "disabled_visible"
  | "batch_prediction"
  | "switch_access shortcut"
  | "send_and archive"
  | "picture_in picture"
  | "code_off"
  | "bookmark_remove"
  | "settings_bluetooth"
  | "view_timeline"
  | "123"
  | "satellite_alt"
  | "flip_to front"
  | "assured_workload"
  | "shop_two"
  | "event_repeat"
  | "work_history"
  | "display_settings"
  | "gif_box"
  | "speaker_notes off"
  | "webhook"
  | "eject"
  | "settings_input hdmi"
  | "perm_data setting"
  | "alarm_off"
  | "html"
  | "perm_scan wifi"
  | "hourglass_disabled"
  | "settings_cell"
  | "app_blocking"
  | "work_off"
  | "output"
  | "sensors_off"
  | "line_style"
  | "pan_tool alt"
  | "noise_control off"
  | "switch_access shortcut add"
  | "picture_in picture alt"
  | "perm_device information"
  | "subtitles_off"
  | "manage_history"
  | "update_disabled"
  | "voice_over off"
  | "settings_input svideo"
  | "app_shortcut"
  | "javascript"
  | "swipe_left"
  | "join_full"
  | "flip_to back"
  | "view_array"
  | "private_connectivity"
  | "open_in new off"
  | "abc"
  | "all_out"
  | "label_off"
  | "swipe_right"
  | "rounded_corner"
  | "shop_2"
  | "install_desktop"
  | "tab_unselected"
  | "swipe_up"
  | "join_inner"
  | "text_rotate vertical"
  | "lightbulb_circle"
  | "explore_off"
  | "text_rotation none"
  | "density_small"
  | "not_accessible"
  | "data_thresholding"
  | "pin_invoke"
  | "commit"
  | "troubleshoot"
  | "install_mobile"
  | "perm_camera mic"
  | "extension_off"
  | "swipe_down"
  | "lightbulb_outline"
  | "view_kanban"
  | "css"
  | "pin_end"
  | "join_left"
  | "home_filled"
  | "pinch"
  | "swipe_vertical"
  | "lock_outline"
  | "view_cozy"
  | "text_rotate up"
  | "text_rotation down"
  | "join_right"
  | "text_rotation angledown"
  | "text_rotation angleup"
  | "spatial_audio off"
  | "edit_document"
  | "lock_person"
  | "outgoing_mail"
  | "swipe_right alt"
  | "noise_aware"
  | "php"
  | "view_comfy alt"
  | "browse_gallery"
  | "arrow_outward"
  | "view_compact alt"
  | "swipe_down alt"
  | "network_ping"
  | "filter_list alt"
  | "density_large"
  | "swipe_left alt"
  | "edit_square"
  | "on_device training"
  | "swipe_up alt"
  | "spatial_tracking"
  | "spatial_audio"
  | "add_home"
  | "label_important outline"
  | "unfold_more double"
  | "hls"
  | "width_full"
  | "hls_off"
  | "width_normal"
  | "barcode_reader"
  | "width_wide"
  | "unfold_less double"
  | "repartition"
  | "assignment_add"
  | "transcribe"
  | "rebase_edit"
  | "close"
  | "close"
  | "menu"
  | "expand_more"
  | "arrow_back"
  | "chevron_right"
  | "arrow_forward ios"
  | "arrow_back ios"
  | "cancel"
  | "arrow_drop down"
  | "more_vert"
  | "arrow_forward"
  | "chevron_left"
  | "check"
  | "expand_less"
  | "more_horiz"
  | "refresh"
  | "apps"
  | "payments"
  | "arrow_upward"
  | "east"
  | "campaign"
  | "arrow_back ios new"
  | "arrow_downward"
  | "arrow_right"
  | "menu_open"
  | "fullscreen"
  | "double_arrow"
  | "arrow_drop up"
  | "unfold_more"
  | "maps_home work"
  | "west"
  | "arrow_left"
  | "south"
  | "expand_circle down"
  | "north"
  | "north_east"
  | "home_work"
  | "first_page"
  | "fullscreen_exit"
  | "arrow_drop down circle"
  | "last_page"
  | "unfold_less"
  | "subdirectory_arrow right"
  | "legend_toggle"
  | "south_east"
  | "app_settings alt"
  | "assistant_direction"
  | "subdirectory_arrow left"
  | "north_west"
  | "switch_left"
  | "waterfall_chart"
  | "south_west"
  | "switch_right"
  | "pivot_table chart"
  | "apps_outage"
  | "offline_share"
  | "assistant_navigation"
  | "add_home work"
  | "person"
  | "person"
  | "notifications"
  | "groups"
  | "people"
  | "share"
  | "person_outline"
  | "school"
  | "person_add"
  | "public"
  | "emoji_events"
  | "group"
  | "notifications_active"
  | "engineering"
  | "construction"
  | "people_alt"
  | "group_add"
  | "psychology"
  | "health_and safety"
  | "travel_explore"
  | "water_drop"
  | "thumb_up alt"
  | "notifications_none"
  | "emoji_emotions"
  | "sports_esports"
  | "sentiment_satisfied"
  | "location_city"
  | "ios_share"
  | "sentiment_very satisfied"
  | "person_add alt"
  | "precision_manufacturing"
  | "emoji_objects"
  | "science"
  | "military_tech"
  | "history_edu"
  | "cake"
  | "sentiment_dissatisfied"
  | "workspace_premium"
  | "coronavirus"
  | "sentiment_very dissatisfied"
  | "emoji_people"
  | "self_improvement"
  | "person_remove"
  | "poll"
  | "handshake"
  | "sports_soccer"
  | "whatshot"
  | "domain"
  | "female"
  | "mood"
  | "recommend"
  | "people_outline"
  | "male"
  | "person_off"
  | "recycling"
  | "person_add alt 1"
  | "sentiment_neutral"
  | "masks"
  | "connect_without contact"
  | "back_hand"
  | "hiking"
  | "architecture"
  | "notifications_off"
  | "waving_hand"
  | "luggage"
  | "thumb_down alt"
  | "front_hand"
  | "mood_bad"
  | "real_estate agent"
  | "emoji_nature"
  | "vaccines"
  | "switch_account"
  | "catching_pokemon"
  | "nights_stay"
  | "king_bed"
  | "interests"
  | "sports_basketball"
  | "notification_add"
  | "emoji_symbols"
  | "compost"
  | "sports_kabaddi"
  | "sports"
  | "reduce_capacity"
  | "emoji_food beverage"
  | "sick"
  | "emoji_transportation"
  | "sports_tennis"
  | "man"
  | "cookie"
  | "transgender"
  | "cruelty_free"
  | "outdoor_grill"
  | "elderly"
  | "deck"
  | "social_distance"
  | "add_moderator"
  | "heart_broken"
  | "follow_the signs"
  | "woman"
  | "plus_one"
  | "clean_hands"
  | "piano"
  | "fireplace"
  | "add_reaction"
  | "sanitizer"
  | "personal_injury"
  | "surfing"
  | "sports_motorsports"
  | "pix"
  | "sports_handball"
  | "sports_baseball"
  | "edit_notifications"
  | "scale"
  | "sports_volleyball"
  | "pages"
  | "sports_football"
  | "hive"
  | "diversity_3"
  | "wallet"
  | "downhill_skiing"
  | "kayaking"
  | "public_off"
  | "single_bed"
  | "skateboarding"
  | "remove_moderator"
  | "notifications_paused"
  | "safety_divider"
  | "group_remove"
  | "person_remove alt 1"
  | "co2"
  | "boy"
  | "sports_cricket"
  | "fitbit"
  | "group_off"
  | "sports_mma"
  | "nordic_walking"
  | "sports_golf"
  | "domain_add"
  | "diversity_1"
  | "paragliding"
  | "6_ft apart"
  | "girl"
  | "sports_martial arts"
  | "snowboarding"
  | "party_mode"
  | "kitesurfing"
  | "groups_2"
  | "snowshoeing"
  | "sports_hockey"
  | "ice_skating"
  | "sports_rugby"
  | "sports_gymnastics"
  | "psychology_alt"
  | "thunderstorm"
  | "south_america"
  | "diversity_2"
  | "sledding"
  | "elderly_woman"
  | "scoreboard"
  | "groups_3"
  | "no_luggage"
  | "face_6"
  | "face_3"
  | "piano_off"
  | "sign_language"
  | "person_2"
  | "cyclone"
  | "scuba_diving"
  | "face_2"
  | "flood"
  | "face_4"
  | "tsunami"
  | "roller_skating"
  | "face_5"
  | "person_4"
  | "severe_cold"
  | "tornado"
  | "landslide"
  | "person_3"
  | "volcano"
  | "18_up rating"
  | "no_adult content"
  | "assist_walker"
  | "woman_2"
  | "man_2"
  | "blind"
  | "dew_point"
  | "man_4"
  | "man_3"
  | "add"
  | "add"
  | "add_circle outline"
  | "content_copy"
  | "add_circle"
  | "send"
  | "clear"
  | "mail"
  | "save"
  | "link"
  | "remove"
  | "filter_list"
  | "inventory_2"
  | "inventory"
  | "insights"
  | "remove_circle outline"
  | "sort"
  | "bolt"
  | "flag"
  | "reply"
  | "add_box"
  | "remove_circle"
  | "push_pin"
  | "block"
  | "create"
  | "calculate"
  | "undo"
  | "how_to reg"
  | "content_paste"
  | "report"
  | "file_copy"
  | "backspace"
  | "shield"
  | "archive"
  | "save_alt"
  | "policy"
  | "tag"
  | "change_circle"
  | "redo"
  | "content_cut"
  | "forward"
  | "inbox"
  | "outlined_flag"
  | "drafts"
  | "link_off"
  | "ballot"
  | "biotech"
  | "report_gmailerrorred"
  | "stacked_bar chart"
  | "delete_sweep"
  | "markunread"
  | "square_foot"
  | "stream"
  | "add_link"
  | "where_to vote"
  | "move_to inbox"
  | "copy_all"
  | "dynamic_feed"
  | "waves"
  | "unarchive"
  | "reply_all"
  | "select_all"
  | "content_paste search"
  | "low_priority"
  | "text_format"
  | "font_download"
  | "weekend"
  | "how_to vote"
  | "upcoming"
  | "gesture"
  | "save_as"
  | "attribution"
  | "content_paste go"
  | "flag_circle"
  | "next_week"
  | "filter_list off"
  | "content_paste off"
  | "report_off"
  | "font_download off"
  | "deselect"
  | "web_stories"
  | "block_flipped"
  | "edit"
  | "edit"
  | "navigate_next"
  | "photo_camera"
  | "image"
  | "tune"
  | "picture_as pdf"
  | "receipt_long"
  | "circle"
  | "timer"
  | "auto_stories"
  | "collections"
  | "navigate_before"
  | "add_a photo"
  | "auto_awesome"
  | "palette"
  | "remove_red eye"
  | "music_note"
  | "add_photo alternate"
  | "wb_sunny"
  | "brush"
  | "flash_on"
  | "euro"
  | "control_point"
  | "auto_fix high"
  | "looks_one"
  | "style"
  | "adjust"
  | "straighten"
  | "photo_library"
  | "camera"
  | "portrait"
  | "camera_alt"
  | "audiotrack"
  | "video_camera front"
  | "rotate_right"
  | "grid_on"
  | "color_lens"
  | "crop_free"
  | "timelapse"
  | "landscape"
  | "slideshow"
  | "collections_bookmark"
  | "crop_square"
  | "currency_rupee"
  | "looks_two"
  | "panorama_fish eye"
  | "lens"
  | "filter_vintage"
  | "filter_drama"
  | "compare"
  | "auto_awesome motion"
  | "healing"
  | "image_search"
  | "looks_3"
  | "rotate_left"
  | "crop"
  | "blur_on"
  | "center_focus strong"
  | "wb_incandescent"
  | "flare"
  | "wb_cloudy"
  | "face_retouching natural"
  | "cases"
  | "colorize"
  | "assistant"
  | "filter_none"
  | "brightness_4"
  | "broken_image"
  | "filter_center focus"
  | "dehaze"
  | "nature_people"
  | "crop_original"
  | "photo"
  | "auto_awesome mosaic"
  | "flash_off"
  | "brightness_6"
  | "tag_faces"
  | "brightness_5"
  | "details"
  | "auto_fix normal"
  | "flip_camera android"
  | "grain"
  | "flip"
  | "brightness_1"
  | "loupe"
  | "flip_camera ios"
  | "image_not supported"
  | "movie_creation"
  | "filter_1"
  | "add_to photos"
  | "panorama"
  | "view_comfy"
  | "animation"
  | "center_focus weak"
  | "movie_filter"
  | "looks_4"
  | "bedtime"
  | "crop_din"
  | "filter"
  | "control_point duplicate"
  | "brightness_7"
  | "leak_add"
  | "nature"
  | "texture"
  | "photo_size select actual"
  | "incomplete_circle"
  | "video_camera back"
  | "timer_off"
  | "view_compact"
  | "transform"
  | "currency_bitcoin"
  | "motion_photos on"
  | "photo_camera front"
  | "rotate_90 degrees ccw"
  | "mic_external on"
  | "gradient"
  | "looks_5"
  | "assistant_photo"
  | "music_off"
  | "hide_image"
  | "exposure_plus 1"
  | "currency_yen"
  | "thermostat_auto"
  | "contrast"
  | "photo_album"
  | "shutter_speed"
  | "exposure"
  | "filter_2"
  | "wb_twilight"
  | "currency_pound"
  | "filter_tilt shift"
  | "crop_16 9"
  | "hdr_strong"
  | "vrpano"
  | "looks"
  | "blur_circular"
  | "linked_camera"
  | "motion_photos auto"
  | "flash_auto"
  | "brightness_3"
  | "looks_6"
  | "crop_portrait"
  | "tonality"
  | "iso"
  | "brightness_2"
  | "photo_filter"
  | "photo_size select small"
  | "crop_7 5"
  | "filter_hdr"
  | "crop_rotate"
  | "hdr_weak"
  | "photo_size select large"
  | "filter_3"
  | "rotate_90 degrees cw"
  | "exposure_zero"
  | "camera_front"
  | "crop_5 4"
  | "filter_frames"
  | "burst_mode"
  | "camera_roll"
  | "currency_ruble"
  | "logo_dev"
  | "blur_linear"
  | "filter_b and w"
  | "crop_3 2"
  | "crop_landscape"
  | "switch_camera"
  | "switch_video"
  | "filter_7"
  | "exposure_plus 2"
  | "filter_4"
  | "filter_9 plus"
  | "motion_photos paused"
  | "wb_iridescent"
  | "monochrome_photos"
  | "grid_off"
  | "photo_camera back"
  | "filter_5"
  | "face_retouching off"
  | "auto_fix off"
  | "exposure_neg 1"
  | "panorama_photosphere"
  | "leak_remove"
  | "filter_8"
  | "filter_9"
  | "timer_10"
  | "video_stable"
  | "wb_shade"
  | "filter_6"
  | "motion_photos off"
  | "blur_off"
  | "raw_on"
  | "hdr_on"
  | "motion_photos pause"
  | "panorama_horizontal"
  | "vignette"
  | "dirty_lens"
  | "image_aspect ratio"
  | "30fps_select"
  | "camera_rear"
  | "timer_3"
  | "panorama_wide angle select"
  | "60fps_select"
  | "24mp"
  | "exposure_neg 2"
  | "deblur"
  | "autofps_select"
  | "panorama_horizontal select"
  | "currency_yuan"
  | "panorama_wide angle"
  | "panorama_photosphere select"
  | "currency_lira"
  | "wb_auto"
  | "hdr_plus"
  | "mic_external off"
  | "panorama_vertical select"
  | "panorama_vertical"
  | "hdr_enhanced select"
  | "12mp"
  | "hevc"
  | "mp"
  | "18mp"
  | "23mp"
  | "currency_franc"
  | "hdr_off"
  | "raw_off"
  | "10mp"
  | "11mp"
  | "20mp"
  | "3mp"
  | "16mp"
  | "bedtime_off"
  | "13mp"
  | "15mp"
  | "5mp"
  | "22mp"
  | "2mp"
  | "17mp"
  | "21mp"
  | "8mp"
  | "14mp"
  | "9mp"
  | "19mp"
  | "4mp"
  | "7mp"
  | "6mp"
  | "wb_twighlight"
  | "email"
  | "email"
  | "location_on"
  | "call"
  | "phone"
  | "business"
  | "chat"
  | "mail_outline"
  | "list_alt"
  | "vpn_key"
  | "qr_code scanner"
  | "chat_bubble outline"
  | "alternate_email"
  | "forum"
  | "chat_bubble"
  | "textsms"
  | "contact_mail"
  | "person_search"
  | "qr_code 2"
  | "qr_code"
  | "sentiment_satisfied alt"
  | "message"
  | "comment"
  | "contacts"
  | "import_contacts"
  | "app_registration"
  | "key"
  | "contact_phone"
  | "import_export"
  | "live_help"
  | "forward_to inbox"
  | "hourglass_bottom"
  | "rss_feed"
  | "hourglass_top"
  | "mark_email read"
  | "read_more"
  | "more_time"
  | "mark_email unread"
  | "document_scanner"
  | "call_end"
  | "hub"
  | "clear_all"
  | "dialpad"
  | "phone_enabled"
  | "mark_chat unread"
  | "3p"
  | "cancel_presentation"
  | "screen_share"
  | "call_made"
  | "call_split"
  | "unsubscribe"
  | "present_to all"
  | "domain_verification"
  | "mark_chat read"
  | "add_ic call"
  | "phonelink_ring"
  | "stay_current portrait"
  | "call_received"
  | "phonelink_lock"
  | "co_present"
  | "phone_disabled"
  | "duo"
  | "ring_volume"
  | "phonelink_setup"
  | "location_off"
  | "stay_primary portrait"
  | "swap_calls"
  | "voicemail"
  | "cell_tower"
  | "call_merge"
  | "mobile_screen share"
  | "phonelink_erase"
  | "person_add disabled"
  | "domain_disabled"
  | "call_missed outgoing"
  | "speaker_phone"
  | "cell_wifi"
  | "desktop_access disabled"
  | "stop_screen share"
  | "spoke"
  | "call_missed"
  | "print_disabled"
  | "pause_presentation"
  | "dialer_sip"
  | "invert_colors off"
  | "rtt"
  | "comments_disabled"
  | "wifi_calling"
  | "portable_wifi off"
  | "mark_unread chat alt"
  | "send_time extension"
  | "stay_current landscape"
  | "sip"
  | "nat"
  | "stay_primary landscape"
  | "no_sim"
  | "key_off"
  | "mail_lock"
  | "contact_emergency"
  | "vpn_key off"
  | "file_download"
  | "file_download"
  | "file_upload"
  | "download"
  | "folder"
  | "grid_view"
  | "upload_file"
  | "cloud_upload"
  | "folder_open"
  | "text_snippet"
  | "cloud"
  | "request_quote"
  | "cloud_download"
  | "drive_file rename outline"
  | "attachment"
  | "upload"
  | "download_for offline"
  | "create_new folder"
  | "newspaper"
  | "downloading"
  | "folder_shared"
  | "cloud_done"
  | "topic"
  | "workspaces"
  | "cloud_queue"
  | "download_done"
  | "approval"
  | "cloud_off"
  | "drive_file move"
  | "drive_folder upload"
  | "file_download done"
  | "file_open"
  | "attach_email"
  | "cloud_sync"
  | "rule_folder"
  | "cloud_circle"
  | "folder_zip"
  | "snippet_folder"
  | "folder_copy"
  | "file_download off"
  | "difference"
  | "drive_file move rtl"
  | "folder_delete"
  | "folder_off"
  | "format_overline"
  | "workspaces_filled"
  | "workspaces_outline"
  | "drive_file move outline"
  | "file_upload off"
  | "local_shipping"
  | "local_shipping"
  | "place"
  | "menu_book"
  | "local_offer"
  | "badge"
  | "map"
  | "category"
  | "restaurant"
  | "directions_car"
  | "volunteer_activism"
  | "local_fire department"
  | "my_location"
  | "local_mall"
  | "flight"
  | "near_me"
  | "handyman"
  | "directions_run"
  | "restaurant_menu"
  | "layers"
  | "medical_services"
  | "lunch_dining"
  | "directions_walk"
  | "local_hospital"
  | "celebration"
  | "park"
  | "pin_drop"
  | "local_library"
  | "local_atm"
  | "local_activity"
  | "local_cafe"
  | "delivery_dining"
  | "rate_review"
  | "design_services"
  | "person_pin"
  | "directions_bike"
  | "directions_bus"
  | "fastfood"
  | "local_police"
  | "directions_car filled"
  | "zoom_out map"
  | "home_repair service"
  | "local_phone"
  | "local_grocery store"
  | "hotel"
  | "miscellaneous_services"
  | "cleaning_services"
  | "navigation"
  | "person_pin circle"
  | "local_gas station"
  | "train"
  | "local_parking"
  | "local_florist"
  | "directions"
  | "local_post office"
  | "money"
  | "two_wheeler"
  | "diamond"
  | "electrical_services"
  | "traffic"
  | "add_business"
  | "local_bar"
  | "alt_route"
  | "pedal_bike"
  | "directions_boat"
  | "agriculture"
  | "beenhere"
  | "360"
  | "route"
  | "liquor"
  | "factory"
  | "moving"
  | "sailing"
  | "local_airport"
  | "add_location alt"
  | "maps_ugc"
  | "local_dining"
  | "emergency"
  | "warehouse"
  | "local_taxi"
  | "ramen_dining"
  | "hail"
  | "local_drink"
  | "trip_origin"
  | "local_printshop"
  | "theater_comedy"
  | "local_laundry service"
  | "local_pizza"
  | "not_listed location"
  | "directions_bus filled"
  | "add_location"
  | "dinner_dining"
  | "bakery_dining"
  | "transfer_within a station"
  | "terrain"
  | "multiple_stop"
  | "wine_bar"
  | "takeout_dining"
  | "icecream"
  | "forest"
  | "store_mall directory"
  | "museum"
  | "nightlife"
  | "local_pharmacy"
  | "add_road"
  | "set_meal"
  | "hardware"
  | "departure_board"
  | "local_see"
  | "ev_station"
  | "electric_car"
  | "plumbing"
  | "festival"
  | "car_rental"
  | "attractions"
  | "layers_clear"
  | "edit_location"
  | "local_convenience store"
  | "pest_control"
  | "edit_road"
  | "run_circle"
  | "dry_cleaning"
  | "edit_location alt"
  | "edit_attributes"
  | "zoom_in map"
  | "moped"
  | "church"
  | "wrong_location"
  | "car_repair"
  | "local_movies"
  | "satellite"
  | "directions_boat filled"
  | "breakfast_dining"
  | "tram"
  | "taxi_alert"
  | "atm"
  | "soup_kitchen"
  | "medical_information"
  | "transit_enterexit"
  | "subway"
  | "brunch_dining"
  | "electric_bike"
  | "hvac"
  | "signpost"
  | "electric_scooter"
  | "directions_transit"
  | "merge"
  | "straight"
  | "bus_alert"
  | "local_car wash"
  | "local_hotel"
  | "egg"
  | "mode_of travel"
  | "connecting_airports"
  | "streetview"
  | "castle"
  | "directions_subway"
  | "stadium"
  | "compass_calibration"
  | "crisis_alert"
  | "mosque"
  | "location_pin"
  | "electric_rickshaw"
  | "directions_railway"
  | "no_meals"
  | "airline_stops"
  | "electric_moped"
  | "railway_alert"
  | "local_play"
  | "turn_right"
  | "car_crash"
  | "safety_check"
  | "bike_scooter"
  | "snowmobile"
  | "near_me disabled"
  | "pest_control rodent"
  | "fork_right"
  | "directions_transit filled"
  | "airlines"
  | "egg_alt"
  | "turn_left"
  | "no_transfer"
  | "directions_railway filled"
  | "directions_subway filled"
  | "u_turn left"
  | "flight_class"
  | "temple_buddhist"
  | "fort"
  | "kebab_dining"
  | "tire_repair"
  | "no_crash"
  | "temple_hindu"
  | "emergency_share"
  | "synagogue"
  | "u_turn right"
  | "sos"
  | "fork_left"
  | "turn_sharp right"
  | "minor_crash"
  | "roundabout_right"
  | "turn_slight left"
  | "remove_road"
  | "turn_slight right"
  | "screen_rotation alt"
  | "turn_sharp left"
  | "roundabout_left"
  | "emergency_recording"
  | "ramp_left"
  | "ramp_right"
  | "fire_truck"
  | "fire_hydrant alt"
  | "no_meals ouline"
  | "play_arrow"
  | "play_arrow"
  | "play_circle filled"
  | "videocam"
  | "play_circle"
  | "mic"
  | "volume_up"
  | "pause"
  | "play_circle outline"
  | "volume_off"
  | "replay"
  | "library_books"
  | "skip_next"
  | "speed"
  | "stop"
  | "fiber_manual record"
  | "movie"
  | "skip_previous"
  | "playlist_add"
  | "new_releases"
  | "equalizer"
  | "loop"
  | "fast_forward"
  | "web"
  | "video_library"
  | "playlist_add check"
  | "library_add"
  | "mic_off"
  | "pause_circle"
  | "video_call"
  | "subscriptions"
  | "repeat"
  | "stop_circle"
  | "volume_mute"
  | "shuffle"
  | "not_interested"
  | "sort_by alpha"
  | "mic_none"
  | "library_music"
  | "fast_rewind"
  | "videocam_off"
  | "volume_down"
  | "recent_actors"
  | "queue_music"
  | "web_asset"
  | "hearing"
  | "library_add check"
  | "pause_circle filled"
  | "subtitles"
  | "pause_circle outline"
  | "fiber_new"
  | "album"
  | "note"
  | "av_timer"
  | "playlist_play"
  | "games"
  | "radio"
  | "queue"
  | "replay_circle filled"
  | "branding_watermark"
  | "forward_10"
  | "replay_10"
  | "closed_caption"
  | "video_settings"
  | "featured_play list"
  | "control_camera"
  | "playlist_add check circle"
  | "slow_motion video"
  | "add_to queue"
  | "airplay"
  | "high_quality"
  | "repeat_one"
  | "call_to action"
  | "snooze"
  | "playlist_remove"
  | "hd"
  | "closed_caption off"
  | "repeat_on"
  | "replay_30"
  | "featured_video"
  | "shuffle_on"
  | "5g"
  | "forward_30"
  | "music_video"
  | "replay_5"
  | "queue_play next"
  | "playlist_add circle"
  | "art_track"
  | "hearing_disabled"
  | "forward_5"
  | "audio_file"
  | "interpreter_mode"
  | "explicit"
  | "video_file"
  | "4k"
  | "fiber_smart record"
  | "video_label"
  | "repeat_one on"
  | "closed_caption disabled"
  | "remove_from queue"
  | "surround_sound"
  | "play_disabled"
  | "web_asset off"
  | "sd"
  | "missed_video call"
  | "10k"
  | "fiber_pin"
  | "fiber_dvr"
  | "lyrics"
  | "4k_plus"
  | "1k"
  | "2k"
  | "1k_plus"
  | "8k"
  | "9k_plus"
  | "8k_plus"
  | "5k"
  | "3k"
  | "5k_plus"
  | "2k_plus"
  | "6k_plus"
  | "7k_plus"
  | "9k"
  | "3k_plus"
  | "7k"
  | "6k"
  | "volume_down alt"
  | "movie_edit"
  | "star"
  | "star"
  | "check_box"
  | "check_box outline blank"
  | "radio_button unchecked"
  | "radio_button checked"
  | "star_border"
  | "toggle_on"
  | "star_outline"
  | "toggle_off"
  | "star_half"
  | "indeterminate_check box"
  | "star_purple500"
  | "star_border purple500"
  | "warning"
  | "warning"
  | "error"
  | "error_outline"
  | "warning_amber"
  | "notification_important"
  | "add_alert"
  | "auto_delete"
  | "attach_money"
  | "attach_money"
  | "format_list bulleted"
  | "edit_note"
  | "mode_edit"
  | "monetization_on"
  | "attach_file"
  | "post_add"
  | "bar_chart"
  | "checklist"
  | "drag_handle"
  | "insert_drive file"
  | "show_chart"
  | "format_quote"
  | "format_list numbered"
  | "border_color"
  | "table_chart"
  | "query_stats"
  | "pie_chart"
  | "notes"
  | "format_bold"
  | "text_fields"
  | "insert_photo"
  | "table_rows"
  | "insert_emoticon"
  | "title"
  | "publish"
  | "auto_graph"
  | "checklist_rtl"
  | "mode"
  | "insert_chart outlined"
  | "mode_comment"
  | "draw"
  | "functions"
  | "insert_link"
  | "insert_invitation"
  | "mode_edit outline"
  | "format_italic"
  | "format_align left"
  | "horizontal_rule"
  | "format_color fill"
  | "add_comment"
  | "insert_chart"
  | "linear_scale"
  | "format_size"
  | "stacked_line chart"
  | "format_underlined"
  | "bubble_chart"
  | "insert_comment"
  | "money_off"
  | "vertical_align bottom"
  | "height"
  | "vertical_align top"
  | "format_align center"
  | "schema"
  | "format_paint"
  | "area_chart"
  | "format_color text"
  | "format_align right"
  | "scatter_plot"
  | "format_list numbered rtl"
  | "square"
  | "highlight"
  | "format_align justify"
  | "merge_type"
  | "add_chart"
  | "format_shapes"
  | "data_object"
  | "numbers"
  | "money_off csred"
  | "pie_chart outline"
  | "short_text"
  | "format_indent increase"
  | "strikethrough_s"
  | "align_horizontal left"
  | "vertical_align center"
  | "format_color reset"
  | "multiline_chart"
  | "move_up"
  | "hexagon"
  | "score"
  | "rectangle"
  | "border_all"
  | "format_indent decrease"
  | "space_bar"
  | "format_clear"
  | "move_down"
  | "format_line spacing"
  | "align_vertical bottom"
  | "horizontal_distribute"
  | "align_horizontal center"
  | "text_increase"
  | "candlestick_chart"
  | "format_strikethrough"
  | "align_horizontal right"
  | "vertical_distribute"
  | "superscript"
  | "polyline"
  | "margin"
  | "wrap_text"
  | "data_array"
  | "align_vertical center"
  | "align_vertical top"
  | "border_clear"
  | "subscript"
  | "pentagon"
  | "border_style"
  | "padding"
  | "border_outer"
  | "text_decrease"
  | "line_axis"
  | "insert_page break"
  | "border_inner"
  | "border_left"
  | "border_bottom"
  | "format_textdirection l to r"
  | "border_vertical"
  | "border_horizontal"
  | "format_textdirection r to l"
  | "border_top"
  | "border_right"
  | "shape_line"
  | "format_list bulleted add"
  | "type_specimen"
  | "pie_chart outlined"
  | "support_agent"
  | "support_agent"
  | "wifi"
  | "account_tree"
  | "sync"
  | "priority_high"
  | "event_available"
  | "phone_in talk"
  | "event_note"
  | "confirmation_number"
  | "sms"
  | "live_tv"
  | "ondemand_video"
  | "wifi_off"
  | "drive_eta"
  | "event_busy"
  | "do_not disturb on"
  | "wc"
  | "more"
  | "power"
  | "do_not disturb"
  | "sync_problem"
  | "time_to leave"
  | "vpn_lock"
  | "do_disturb on"
  | "running_with errors"
  | "folder_special"
  | "enhanced_encryption"
  | "do_disturb"
  | "network_check"
  | "sms_failed"
  | "phone_callback"
  | "adb"
  | "system_update"
  | "power_off"
  | "phone_forwarded"
  | "personal_video"
  | "voice_chat"
  | "vibration"
  | "do_disturb alt"
  | "airline_seat recline normal"
  | "do_not disturb alt"
  | "sync_disabled"
  | "tap_and play"
  | "no_encryption"
  | "sd_card"
  | "phone_missed"
  | "airline_seat recline extra"
  | "imagesearch_roller"
  | "mms"
  | "disc_full"
  | "bluetooth_audio"
  | "no_encryption gmailerrorred"
  | "sd_card alert"
  | "sim_card alert"
  | "do_not disturb off"
  | "airline_seat individual suite"
  | "phone_paused"
  | "sync_lock"
  | "do_disturb off"
  | "airline_seat flat"
  | "phone_locked"
  | "network_locked"
  | "airline_seat flat angled"
  | "tv_off"
  | "phone_bluetooth speaker"
  | "directions_off"
  | "airline_seat legroom normal"
  | "airline_seat legroom extra"
  | "airline_seat legroom reduced"
  | "add_call"
  | "video_chat"
  | "keyboard_arrow down"
  | "keyboard_arrow down"
  | "phone_iphone"
  | "smartphone"
  | "keyboard_arrow right"
  | "computer"
  | "security"
  | "desktop_windows"
  | "smart_display"
  | "keyboard_backspace"
  | "phone_android"
  | "keyboard_arrow up"
  | "laptop"
  | "keyboard_arrow left"
  | "smart_toy"
  | "keyboard_double arrow right"
  | "keyboard_return"
  | "headphones"
  | "keyboard"
  | "memory"
  | "point_of sale"
  | "headset_mic"
  | "tv"
  | "keyboard_double arrow left"
  | "mouse"
  | "keyboard_voice"
  | "keyboard_double arrow down"
  | "developer_board"
  | "router"
  | "videogame_asset"
  | "cast_for education"
  | "device_hub"
  | "keyboard_double arrow up"
  | "headset"
  | "laptop_mac"
  | "start"
  | "cast"
  | "watch"
  | "tablet_mac"
  | "devices_other"
  | "desktop_mac"
  | "keyboard_tab"
  | "laptop_chromebook"
  | "phonelink"
  | "monitor"
  | "speaker"
  | "toys"
  | "gamepad"
  | "keyboard_alt"
  | "sim_card"
  | "connected_tv"
  | "tablet_android"
  | "cast_connected"
  | "laptop_windows"
  | "device_unknown"
  | "keyboard_hide"
  | "browser_updated"
  | "scanner"
  | "tablet"
  | "speaker_group"
  | "keyboard_capslock"
  | "earbuds"
  | "headset_off"
  | "home_max"
  | "headphones_battery"
  | "keyboard_command key"
  | "smart_screen"
  | "power_input"
  | "dock"
  | "browser_not supported"
  | "earbuds_battery"
  | "home_mini"
  | "phonelink_off"
  | "developer_board off"
  | "adf_scanner"
  | "videogame_asset off"
  | "keyboard_control key"
  | "watch_off"
  | "keyboard_option key"
  | "pallet"
  | "trolley"
  | "conveyor_belt"
  | "forklift"
  | "front_loader"
  | "light_mode"
  | "light_mode"
  | "restart_alt"
  | "dark_mode"
  | "task"
  | "summarize"
  | "password"
  | "sell"
  | "signal_cellular alt"
  | "devices"
  | "settings_suggest"
  | "quiz"
  | "widgets"
  | "storage"
  | "thermostat"
  | "credit_score"
  | "battery_full"
  | "gps_fixed"
  | "price_check"
  | "medication"
  | "pin"
  | "gpp_good"
  | "price_change"
  | "tungsten"
  | "battery_charging full"
  | "fmd_good"
  | "reviews"
  | "note_alt"
  | "air"
  | "graphic_eq"
  | "bluetooth"
  | "dvr"
  | "nightlight"
  | "sports_score"
  | "access_time"
  | "monitor_heart"
  | "water"
  | "share_location"
  | "gpp_maybe"
  | "location_searching"
  | "cable"
  | "cameraswitch"
  | "shortcut"
  | "airplane_ticket"
  | "device_thermostat"
  | "wallpaper"
  | "radar"
  | "data_usage"
  | "signal_wifi 4 bar"
  | "gpp_bad"
  | "monitor_weight"
  | "developer_mode"
  | "battery_std"
  | "mode_night"
  | "wifi_tethering"
  | "bloodtype"
  | "signal_cellular 4 bar"
  | "discount"
  | "flashlight_on"
  | "fmd_bad"
  | "splitscreen"
  | "network_wifi"
  | "sim_card download"
  | "access_time filled"
  | "airplanemode_active"
  | "mobile_friendly"
  | "send_to mobile"
  | "battery_alert"
  | "usb"
  | "screen_search desktop"
  | "lens_blur"
  | "signal_wifi statusbar 4 bar"
  | "lan"
  | "screen_rotation"
  | "signal_wifi statusbar connected no internet 4"
  | "system_security update good"
  | "gps_not fixed"
  | "bluetooth_connected"
  | "remember_me"
  | "pattern"
  | "nfc"
  | "mode_standby"
  | "brightness_high"
  | "battery_saver"
  | "play_lesson"
  | "storm"
  | "data_saver off"
  | "brightness_medium"
  | "signal_wifi 0 bar"
  | "brightness_low"
  | "network_cell"
  | "screenshot"
  | "data_saver on"
  | "bluetooth_searching"
  | "grid_4x4"
  | "mobiledata_off"
  | "ad_units"
  | "battery_5 bar"
  | "bluetooth_disabled"
  | "hdr_auto"
  | "security_update good"
  | "battery_unknown"
  | "signal_wifi off"
  | "settings_system daydream"
  | "signal_wifi bad"
  | "ssid_chart"
  | "wifi_calling 3"
  | "battery_4 bar"
  | "access_alarms"
  | "signal_wifi connected no internet 4"
  | "battery_0 bar"
  | "aod"
  | "add_to home screen"
  | "battery_6 bar"
  | "signal_cellular 0 bar"
  | "flashlight_off"
  | "security_update"
  | "access_alarm"
  | "gps_off"
  | "4g_mobiledata"
  | "signal_wifi statusbar null"
  | "grid_3x3"
  | "sd_storage"
  | "battery_3 bar"
  | "reset_tv"
  | "brightness_auto"
  | "wifi_lock"
  | "signal_cellular connected no internet 4 bar"
  | "do_not disturb on total silence"
  | "airplanemode_inactive"
  | "nearby_error"
  | "1x_mobiledata"
  | "security_update warning"
  | "battery_1 bar"
  | "punch_clock"
  | "signal_cellular connected no internet 0 bar"
  | "screen_lock portrait"
  | "medication_liquid"
  | "system_security update"
  | "system_security update warning"
  | "wifi_tethering off"
  | "battery_2 bar"
  | "edgesensor_high"
  | "wifi_password"
  | "4g_plus mobiledata"
  | "signal_cellular off"
  | "signal_wifi 4 bar lock"
  | "signal_cellular nodata"
  | "lte_mobiledata"
  | "phishing"
  | "add_alarm"
  | "location_disabled"
  | "bluetooth_drive"
  | "media_bluetooth on"
  | "mobile_off"
  | "screenshot_monitor"
  | "signal_cellular null"
  | "30fps"
  | "rsvp"
  | "grid_goldenratio"
  | "3g_mobiledata"
  | "edgesensor_low"
  | "screen_lock rotation"
  | "60fps"
  | "screen_lock landscape"
  | "lte_plus mobiledata"
  | "usb_off"
  | "network_wifi 1 bar"
  | "timer_10 select"
  | "wifi_find"
  | "network_wifi 3 bar"
  | "dataset"
  | "signal_cellular no sim"
  | "g_mobiledata"
  | "timer_3 select"
  | "network_wifi 2 bar"
  | "wifi_2 bar"
  | "wifi_tethering error"
  | "h_mobiledata"
  | "signal_cellular alt 2 bar"
  | "media_bluetooth off"
  | "wifi_channel"
  | "e_mobiledata"
  | "r_mobiledata"
  | "signal_cellular alt 1 bar"
  | "wifi_1 bar"
  | "h_plus mobiledata"
  | "hdr_on select"
  | "hdr_auto select"
  | "nearby_off"
  | "hdr_off select"
  | "dataset_linked"
  | "devices_fold"
  | "fluorescent"
  | "macro_off"
  | "storefront"
  | "storefront"
  | "apartment"
  | "fitness_center"
  | "business_center"
  | "spa"
  | "house"
  | "meeting_room"
  | "corporate_fare"
  | "ac_unit"
  | "cottage"
  | "family_restroom"
  | "other_houses"
  | "checkroom"
  | "grass"
  | "all_inclusive"
  | "airport_shuttle"
  | "child_care"
  | "beach_access"
  | "pool"
  | "kitchen"
  | "casino"
  | "holiday_village"
  | "roofing"
  | "room_service"
  | "room_preferences"
  | "sports_bar"
  | "free_breakfast"
  | "bathtub"
  | "escalator_warning"
  | "child_friendly"
  | "foundation"
  | "food_bank"
  | "gite"
  | "villa"
  | "night_shelter"
  | "golf_course"
  | "no_photography"
  | "stairs"
  | "microwave"
  | "backpack"
  | "elevator"
  | "smoking_rooms"
  | "wash"
  | "cabin"
  | "house_siding"
  | "hot_tub"
  | "countertops"
  | "water_damage"
  | "fire_extinguisher"
  | "carpenter"
  | "charging_station"
  | "baby_changing station"
  | "soap"
  | "rv_hookup"
  | "umbrella"
  | "smoke_free"
  | "tapas"
  | "rice_bowl"
  | "do_not touch"
  | "balcony"
  | "no_food"
  | "fence"
  | "houseboat"
  | "tty"
  | "bento"
  | "wheelchair_pickup"
  | "iron"
  | "bungalow"
  | "chalet"
  | "crib"
  | "do_not step"
  | "no_meeting room"
  | "escalator"
  | "dry"
  | "stroller"
  | "no_drinks"
  | "no_cell"
  | "no_flash"
  | "no_backpack"
  | "no_stroller"
  | "vaping_rooms"
  | "vape_free"
  | "desk"
  | "manage_search"
  | "manage_search"
  | "feed"
  | "chair"
  | "bed"
  | "podcasts"
  | "coffee"
  | "shower"
  | "yard"
  | "window"
  | "door_front"
  | "light"
  | "garage"
  | "dining"
  | "flatware"
  | "coffee_maker"
  | "blender"
  | "camera_indoor"
  | "bedroom_parent"
  | "table_restaurant"
  | "bathroom"
  | "bedroom_baby"
  | "chair_alt"
  | "door_sliding"
  | "camera_outdoor"
  | "door_back"
  | "living"
  | "doorbell"
  | "bedroom_child"
  | "table_bar"
  | "sensor_door"
  | "sensor_door"
  | "sensor_window"
  | "electric_bolt"
  | "shield_moon"
  | "energy_savings leaf"
  | "solar_power"
  | "auto_mode"
  | "wind_power"
  | "oil_barrel"
  | "sunny"
  | "electric_meter"
  | "heat_pump"
  | "sensor_occupied"
  | "gas_meter"
  | "propane_tank"
  | "mode_fan off"
  | "roller_shades"
  | "propane"
  | "cloudy_snowing"
  | "roller_shades closed"
  | "broadcast_on personal"
  | "blinds_closed"
  | "curtains"
  | "vertical_shades"
  | "blinds"
  | "vertical_shades closed"
  | "curtains_closed"
  | "broadcast_on home"
  | "nest_cam wired stand"
  | "sunny_snowing"
  | "shelves"
  | "snowing"
  | "foggy";
